# SPDX-License-Identifier: MIT
---
- name: Set platform/version specific variables
  include_tasks: tasks/set_vars.yml

- name: Create encrypted disk partition
  include_tasks: encrypt_disk.yml
  when: cvm_deploy_encrypt_disk | bool

- name: Deploy Trustee Guest Components using Podman Quadlets
  include_tasks: trustee_quadlet.yml
  when: cvm_deploy_trustee_gc | bool
